controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_axis_joint_1
      - left_axis_joint_2
      - left_axis_joint_3
      - left_axis_joint_4
      - left_axis_joint_5
      - left_axis_joint_6
  - name: fake_right_arm_controller
    joints:
      - right_axis_joint_1
      - right_axis_joint_2
      - right_axis_joint_3
      - right_axis_joint_4
      - right_axis_joint_5
      - right_axis_joint_6