# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: [left_arm,right_arm]
  joint_model_group_pose: ready_hold
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_axis_joint_1
    - left_axis_joint_2
    - left_axis_joint_3
    - left_axis_joint_4
    - left_axis_joint_5
    - left_axis_joint_6
    - right_axis_joint_1
    - right_axis_joint_2
    - right_axis_joint_3
    - right_axis_joint_4
    - right_axis_joint_5
    - right_axis_joint_6
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 125
left_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - left_axis_joint_1
      - left_axis_joint_2
      - left_axis_joint_3
      - left_axis_joint_4
      - left_axis_joint_5
      - left_axis_joint_6
    gains:
        left_axis_joint_1: { p: 1000, d: 1, i: 1, i_clamp: 1 }
        left_axis_joint_2: { p: 1000, d: 0, i: 1, i_clamp: 1 }
        left_axis_joint_3: { p: 80, d: 1, i: 1, i_clamp: 1 }
        left_axis_joint_4: { p: 10, d: 0, i: 1, i_clamp: 1 }
        left_axis_joint_5: { p: 5, d: 0, i: 1, i_clamp: 1 }
        left_axis_joint_6: { p: 1, d: 0, i: 0, i_clamp: 1 }
    constraints:
        goal_time: 2.0
    state_publish_rate: 25
right_arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - right_axis_joint_1
      - right_axis_joint_2
      - right_axis_joint_3
      - right_axis_joint_4
      - right_axis_joint_5
      - right_axis_joint_6
    gains:
        right_axis_joint_1: { p: 1000, d: 1, i: 1, i_clamp: 1 }
        right_axis_joint_2: { p: 1000, d: 0, i: 1, i_clamp: 1 }
        right_axis_joint_3: { p: 80, d: 1, i: 1, i_clamp: 1 }
        right_axis_joint_4: { p: 10, d: 0, i: 1, i_clamp: 1 }
        right_axis_joint_5: { p: 5, d: 0, i: 1, i_clamp: 1 }
        right_axis_joint_6: { p: 1, d: 0, i: 0, i_clamp: 1 }
    constraints:
        goal_time: 2.0
    state_publish_rate: 25
controller_list:
    - name: left_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
      - left_axis_joint_1
      - left_axis_joint_2
      - left_axis_joint_3
      - left_axis_joint_4
      - left_axis_joint_5
      - left_axis_joint_6
    - name: right_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
      - right_axis_joint_1
      - right_axis_joint_2
      - right_axis_joint_3
      - right_axis_joint_4
      - right_axis_joint_5
      - right_axis_joint_6