controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_axis_joint_1
      - left_axis_joint_2
      - left_axis_joint_3
      - left_axis_joint_4
      - left_axis_joint_5
      - left_axis_joint_6
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_axis_joint_1
      - right_axis_joint_2
      - right_axis_joint_3
      - right_axis_joint_4
      - right_axis_joint_5
      - right_axis_joint_6
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: home
  - group: right_arm
    pose: home