left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_axis_joint_1
    - left_axis_joint_2
    - left_axis_joint_3
    - left_axis_joint_4
    - left_axis_joint_5
    - left_axis_joint_6
  gains:
    left_axis_joint_1:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    left_axis_joint_2:
      p: 1000
      d: 0
      i: 1
      i_clamp: 1
    left_axis_joint_3:
      p: 80
      d: 1
      i: 1
      i_clamp: 1
    left_axis_joint_4:
      p: 10
      d: 0
      i: 1
      i_clamp: 1
    left_axis_joint_5:
      p: 5
      d: 0.01
      i: 1
      i_clamp: 1
    left_axis_joint_6:
      p: 1
      d: 0.01
      i: 0
      i_clamp: 1
right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_axis_joint_1
    - right_axis_joint_2
    - right_axis_joint_3
    - right_axis_joint_4
    - right_axis_joint_5
    - right_axis_joint_6
  gains:
    right_axis_joint_1:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    right_axis_joint_2:
      p: 1000
      d: 0
      i: 1
      i_clamp: 1
    right_axis_joint_3:
      p: 80
      d: 1
      i: 1
      i_clamp: 1
    right_axis_joint_4:
      p: 10
      d: 0.01
      i: 1
      i_clamp: 1
    right_axis_joint_5:
      p: 5
      d: 0.01
      i: 1
      i_clamp: 1
    right_axis_joint_6:
      p: 1
      d: 0
      i: 0
      i_clamp: 1