controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_axis_joint_1
      - left_axis_joint_2
      - left_axis_joint_3
      - left_axis_joint_4
      - left_axis_joint_5
      - left_axis_joint_6
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_axis_joint_1
      - right_axis_joint_2
      - right_axis_joint_3
      - right_axis_joint_4
      - right_axis_joint_5
      - right_axis_joint_6