joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_axis_joint_1
    - left_axis_joint_2
    - left_axis_joint_3
    - left_axis_joint_4
    - left_axis_joint_5
    - left_axis_joint_6
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_axis_joint_1
    - right_axis_joint_2
    - right_axis_joint_3
    - right_axis_joint_4
    - right_axis_joint_5
    - right_axis_joint_6